services:
  db:
    image: postgres:16
    container_name: autoflex_db
    environment:
      POSTGRES_DB: autoflex
      POSTGRES_USER: autoflex
      POSTGRES_PASSWORD: autoflex
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U autoflex -d autoflex"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Autoflex.Api/Dockerfile
    container_name: autoflex_api
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=autoflex;Username=autoflex;Password=autoflex
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  # containerizar o frontend
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: autoflex_frontend
    environment:
      VITE_API_BASE_URL: http://localhost:8080/api
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  pgdata:
